graph LR;
    A[Observaciones sobre los sistemas acuáticos] --> B[Planicies de inundación del Caribe];
    A --> C[Sistemas de la región andina];
    B --> D[Rasgos especiales: acinetos, aerótopos, heterocitos];
    D --> E[Lagos de inundación amazónicos, Laguna Fúquene];
    E --> F[Flagelos];
    C --> G[Lago Tota];
    G --> H[Mucílago];
    C --> I[Ciénaga de Ayapel];
    I --> J[Estructuras silíceas];
    A --> K[Clasificación morfológica y funcional del fitoplancton];
    K --> L[Rasgos morfológicos continuos y categóricos];
    L --> M[Coherencia en la relación];
    M --> N[Grupo VII: Mayor volumen, menor relación superficie-volumen];
    M --> O[Grupo III: Mayor dimensión lineal máxima, mayor relación superficie-volumen];
    O --> P[Adaptaciones en planicies de inundación];
    N --> Q[Rasgos morfológicos numéricos];
    O --> R[Ambientes caracterizados por constantes mezclas de agua];
    R --> S[Asociación inversa entre profundidad fótica y relación superficie-volumen, presencia de aerótopos y mucílago];
    S --> T[Favorecen flotabilidad y reducen pérdidas por sedimentación];
    S --> U[Relación positiva entre relación superficie-volumen y disponibilidad de nutrientes];
    U --> V[Mayor interacción con el ambiente];
